### ISSUE TITLE
parse json from antiSMASH

### ISSUE THREAD

**Issue by drelo** [ostash-group/BGCViz#1]
Dear Pavlo, 

The app looks wonderful and it is really useful to compare these outputs but I have a request or suggestion, is there a way to parse the .json output from antiSMASH to either convert it to .tsv or to use it as input to BGCViz? 
The current version of antiSMASH (after 5.0.0) opted for the .json format and abandoned the .tsv output.

Cheers

**Comment by pavlohrab** [comment]
Hi drelo,

Sorry for the late reply. For now, unfortunately, there is no automatic way to convert json file to the csv format, only manual generation of the csv file works. Sure, parsing the json file (as an output from antismash) directly to the app is a very promising improvement. I will add that to the future upgrades! 
Thanks for the suggestion!

Pavlo
