### ISSUE TITLE
Uploading PRISM data

### ISSUE THREAD

**Issue by Setis09** [ostash-group/BGCViz#15]
Hi to everyone!

I write here because I want to know if something can be done with an error at the page when I'm uploading the PRISM data files with .json format. The problem is when it's finished the upload of the file, then it throws an error output requesting to refresh the page and try again.

I have tried many times and with different files, but the error persist. I would like to know if there is something I can do to fix it.

Thanks by your attention.

**Comment by pavlohrab** [comment]
Hi!

I suggest to try the local installation as an R package, described [here](https://ostash-group.github.io/BGCViz/#/Installation?id=installation-1), in case you are trying our hosted one. Or the problem persist with the local installation as well?

**Comment by Setis09** [comment]
I'm gonna try with the local installation. Thanks for your help !

**Comment by pavlohrab** [comment]
FYI, I updated the version on the server as well. Now it should works
