### ISSUE TITLE
antismash.R code error

### ISSUE THREAD

**Issue by mhyleung** [ostash-group/BGCViz#6]
Dear all

I was trying to convert my antismash.json output into csv for BGCViz, but I encountered this error:

```
Warning messages:
1: Expected 2 pieces. Additional pieces discarded in 10 rows [38, 65, 149, 171, 184, 185, 201, 206, 306, 310].
2: Expected 2 pieces. Missing pieces filled with `NA` in 297 rows [1, 3, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 17, 19, 20, 21, 22, 23, 24, 25, ...].
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :
  arguments imply differing number of rows: 0, 1
Calls: cbind ... as.data.frame -> as.data.frame.list -> do.call -> <Anonymous>
Execution halted
```

Could someone point to me what the issue is with my input file? It came straight out of my antiSMASH run so I am rather puzzled. Thanks

Marcus

**Comment by pavlohrab** [comment]
Hello, 

Sorry for such long pause, but the BGCViz was updated and now supports the antismash.json input directly. I encourage you to try once more!
